name: Deploy Tailwind CSS to GitHub Pages

on:
  push:
    branches:
      - main # Jalankan action setiap kali ada push ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Pastikan ini sesuai dengan versi Node.js yang kompatibel

      - name: Install dependencies
        run: npm install

      - name: Ensure tailwindcss is executable
        run: chmod +x ./node_modules/.bin/tailwindcss

      - name: Build Tailwind CSS
        run: npm run build # Menjalankan perintah 'npm run build' yang menggunakan npx untuk Tailwind CSS

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Sesuaikan jika folder hasil build ada di lokasi lain
