name: Deploy Tailwind CSS to GitHub Pages

on:
  push:
    branches:
      - main # Trigger action on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Sesuaikan dengan versi Node.js yang Anda gunakan

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run dev # Jalankan perintah build CSS di mode watch

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Mengarahkan ke folder hasil build untuk deployment
