name: Deploy Tailwind CSS to GitHub Pages

on:
  push:
    branches:
      - main # Trigger action on push to main branch

permissions:
  contents: write # Explicitly allows write access for contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Adjust Node.js version as needed

      - name: Install Tailwind CSS Globally
        run: npm install -g tailwindcss

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: tailwindcss -i ./src/input.css -o ./dist/output.css --minify # Directly use the globally installed tailwindcss

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Points to the output folder for deployment
          publish_branch: gh-pages # Ensure it targets the correct branch
